exercises/0120-razor/Pirates.RazorPages/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Pirates.RazorPages.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

exercises/0120-razor/Pirates.RazorPages/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Pirates.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pirates.RazorPages.Pages
{
    public class IndexModel : PageModel
    {
        private readonly PiratesContext context;

        public IEnumerable<Pirate>? Pirates { get; private set; }

        [BindProperty]
        public string? NameFilter { get; set; }

        public IndexModel(PiratesContext context)
        {
            this.context = context;
        }

        public async Task OnGetAsync() => await OnPostFilter();

        public async Task OnPostDelete(Guid id)
        {
            var pirate = await context.Pirates.FirstOrDefaultAsync(p => p.ID == id);
            if (pirate != null)
            {
                context.Pirates.Remove(pirate);
                await context.SaveChangesAsync();
            }

            await OnPostFilter();
        }

        public async Task OnPostFilter()
        {
            IQueryable<Pirate> result = context.Pirates;
            if (!string.IsNullOrEmpty(NameFilter))
            {
                result = result.Where(p => (p.Name != null && p.Name.Contains(NameFilter)) ||
                    (p.RealName != null && p.RealName.Contains(NameFilter)));
            }

            Pirates = await result.ToListAsync();
        }
    }
}

exercises/0120-razor/Pirates.RazorPages/Pages/Pirate.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Pirates.Model;

namespace Pirates.RazorPages.Pages
{
    public class PirateModel : PageModel
    {
        private readonly PiratesContext context;

        public PirateModel(PiratesContext context)
        {
            this.context = context;
            Pirate = new Pirate();
        }

        [BindProperty]
        public Pirate Pirate { get; set; }

        public async Task OnGetAsync()
        {
            var idString = RouteData.Values["id"] as string;
            if (idString != null && Guid.TryParse(idString, out var id))
            {
                var dbPirate = await context.Pirates.FirstOrDefaultAsync(p => p.ID == id);
                if (dbPirate != null) Pirate = dbPirate;
            }
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid && Pirate != null)
            {
                if (RouteData.Values["id"] != null)
                {
                    context.Pirates.Update(Pirate);
                }
                else
                {
                    context.Pirates.Add(Pirate);
                }

                await context.SaveChangesAsync();
                return RedirectToPage("Index");
            }

            return Page();
        }
    }
}

exercises/0120-razor/Pirates.RazorPages/Pages/Index.cshtml
@page
@model IndexModel

<div>
    <h1 class="display-4">Pirates</h1>

    <form asp-page-handler="filter" method="post">
        <div class="mb-3">
            <label for="nameFilter" class="form-label">Name filter</label>
            <input asp-for="NameFilter" class="form-control" id="nameFilter">
        </div>
        <button type="submit" class="btn btn-primary">Filter</button>
    </form>

    @if (Model.Pirates == null || !Model.Pirates.Any())
    {
     <div class="alert alert-primary" role="alert">
      Sorry, no pirates found!
     </div>
    }
    else
    {
     <table class="table table-striped">
      <thead>
       <tr>
        <th scope="col">Name</th>
        <th scope="col">Real Name</th>
        <th scope="col">Year of Birth</th>
        <th scope="col">Year of Death</th>
        <th scope="col">Country of Origin</th>
        <th scope="col">&nbsp;</th>
        <th scope="col">&nbsp;</th>
       </tr>
      </thead>
      <tbody>
        @foreach (var p in Model.Pirates!)
        {
           <tr>
            <td>@(p.Name ?? "☠️")</td>
            <td>@(p.RealName ?? "☠️")</td>
            <td>@p.YearOfBirth</td>
            <td>@p.YearOfDeath</td>
            <td>@p.CountryOfOrigin</td>
            <td>
             <form asp-page-handler="delete" method="post">
              <button class="btn">❌</button>
              <input name="id" type="hidden" value="@p.ID" />
              <input asp-for="NameFilter" type="hidden" />
             </form>
            </td>
            <td>
              <a asp-page="pirate" asp-route-id="@p.ID">✏</a>
            </td>
           </tr>
        }
      </tbody>
     </table>
    }
</div>

exercises/0120-razor/Pirates.RazorPages/Pages/Pirate.cshtml
@page "{id?}"
@model Pirates.RazorPages.Pages.PirateModel

<h1 class="display-4">@(RouteData.Values["id"] != null ? "Edit" : "Create") Pirate</h1>

<form method="post">
  <input asp-for="Pirate.ID" type="hidden">
  <div class="mb-3">
    <label for="Name" class="form-label">Name</label>
    <input asp-for="Pirate.Name" class="form-control" id="Name">
  </div>
  <div class="mb-3">
    <label for="RealName" class="form-label">Real Name</label>
    <input asp-for="Pirate.RealName" class="form-control" id="RealName">
  </div>
  <div class="mb-3">
    <label for="YearOfBirth" class="form-label">Year of Birth</label>
    <input asp-for="Pirate.YearOfBirth" class="form-control" id="YearOfBirth">
  </div>
  <div class="mb-3">
    <label for="YearOfDeath" class="form-label">Year of Death</label>
    <input asp-for="Pirate.YearOfDeath" class="form-control" id="YearOfDeath">
  </div>
  <div class="mb-3">
    <label for="CountryOfOrigin" class="form-label">Country of Origin</label>
    <input asp-for="Pirate.CountryOfOrigin" class="form-control" id="CountryOfOrigin">
    <div class="form-text text-danger">
        <span asp-validation-for="Pirate.CountryOfOrigin"></span>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

exercises/0120-razor/Pirates.RazorPages/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pirates Example</title>
    <link rel="stylesheet" href="~/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Pirates 🦜☠️</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Pirate">Add Pirate</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Example from HTL Leonding
        </div>
    </footer>

    <script src="~/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>